### ISSUE TITLE
trying to run prompt but hitting error

### ISSUE THREAD

**Issue by krrishdholakia** [deepglugs/deep_imagen#3]
Hi, 

I'm training this model on a dataset of pictures of rooms, and running this prompt - "photo of a room". 

But, I'm hitting this issue -

`RuntimeError: PytorchStreamReader failed reading file data/2: file read failed`

Model has been running for nearly the entire day, what exactly is wrong here?

**Comment by krrishdholakia** [comment]
full logs: 

`Traceback (most recent call last):
  File "/usr/local/bin/imagen", line 8, in <module>
    sys.exit(imagen())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/imagen_pytorch/cli.py", line 32, in imagen
    loaded = torch.load(str(model_path))
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 1049, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 1019, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 997, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch._UntypedStorage).storage()._untyped()
RuntimeError: PytorchStreamReader failed reading file data/2: file read failed`

**Comment by deepglugs** [comment]
Looks like your model file might be corrupted.

**Comment by krrishdholakia** [comment]
Hmm, I’m just downloading your repo and running it on the dataset. How would you suggest I proceed on this?

**Comment by deepglugs** [comment]
can you paste your full command line?

**Comment by deepglugs** [comment]
Did you train a model yet? Can you paste your command line?
